{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ucloud-kv-mongodb.labels" . | indent 4 }}
type: Opaque
stringData:
  username: {{ required "auth.username is required" .Values.auth.username | quote }}
  password: {{ required "auth.password is required when auth.createSecret=true" .Values.auth.password | quote }}
{{- end }}
