image:
  repository: uhub.service.ucloud.cn/uminfer-proxy/ucloud-kv-indexer-web
  tag: latest
  pullPolicy: Always

web:
  name: ucloud-kv-web
  replicas: 1
  port: 3000
  gatewayBaseURL: http://kvgateway.ucloud-kv-indexers.svc.cluster.local:8095
  service:
    type: ClusterIP
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
