apiVersion: v1
kind: Service
metadata:
  name: {{ include "ucloud-kv-gateway.name" . }}
  namespace: {{ include "ucloud-kv-gateway.namespace" . }}
  labels:
{{ include "ucloud-kv-gateway.labels" . | indent 4 }}
{{- with .Values.gateway.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: kvgateway
