image:
  repository: uhub.service.ucloud.cn/uminfer-proxy/ucloud-kv-indexer
  tag: latest
  pullPolicy: Always

localTokenizer:
  enabled: true
  url: http://127.0.0.1:9000
  port: 9000
  tokenizersRoot: /data/tokenizers
  image:
    repository: uhub.service.ucloud.cn/uminfer-proxy/ucloud-kv-tokenizer-sidecar
    tag: latest
    pullPolicy: Always
  resources: {}
  persistence:
    enabled: false
    existingClaim: ""

secrets:
  create: true
  name: kvgateway-secrets
  backendToken: 70982fdbbb8dc83145eda4b7fb99e55b0be74c0682c4f09c0b406112c10ae002
  mongoURI: mongodb://root:BLR4X6MzK7WbvKn6@10.2.129.72:27017,10.2.43.102:27017,10.2.249.68:27017/?replicaSet=umongodb-rs-1rgl33565z5e

bootstrap:
  enabled: false
  # configMapName: kvgateway-bootstrap
  # files:
  #   th-gb200.yaml: |
  #     clusters:
  #       - cluster_id: th-gb200
  #         display_name: TH GB200 SGLang DeepSeek-V4-Pro
  #         region: th
  #         environment: prod
  #         enabled: true
  #         framework: sglang
  #         backends:
  #           - http://kvindexer-th-gb200.ucloud-kv-indexers.svc.cluster.local:8090
  #         models:
  #           - model_id: "/mnt/nvme4n1/models/deepseek-ai/DeepSeek-V4-Pro"
  #             block_size: 256
  #             hash_seed: "0"
  #             tokenizer_endpoint: http://sglang-deepseek-v4-pro.default.svc.cluster.local:30000/v1/tokenize
  #         engines:
  #           - engine_id: sglang-deepseek-v4-pro
  #             api_endpoint: http://sglang-deepseek-v4-pro.default.svc.cluster.local:30000
  #             tokenizer_endpoint: http://sglang-deepseek-v4-pro.default.svc.cluster.local:30000/v1/tokenize
  #             kv_event_endpoint: tcp://sglang-deepseek-v4-pro.default.svc.cluster.local:5557
  #             replay_endpoint: tcp://sglang-deepseek-v4-pro.default.svc.cluster.local:5565
  #             topic: kv-events
  #             served_models:
  #               - "/mnt/nvme4n1/models/deepseek-ai/DeepSeek-V4-Pro"
  #             dp_ranks: 8
  #             max_model_len: 1048576

gateway:
  name: kvgateway
  replicas: 2
  listenAddress: ":8095"
  port: 8095
  store: mongo
  mongo:
    db: kvgateway
  # configFiles:
  #   - th-gb200.yaml
  service:
    type: ClusterIP
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
